version: "3.9"

services:
  database:
    restart: always
    image: postgres:15.3-alpine3.18
    container_name: msgrelayerdb
    ports:
      - "5445:5432"
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    restart: always
    build: .
    container_name: server
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - database
    command: >
      sh -c "
      python manage.py makemigrations --noinput &&
      python manage.py migrate  --noinput &&
      python manage.py runserver 0.0.0.0:8000"

volumes:
  db-data:
