# Generated by Django 4.2.4 on 2023-08-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramtoken",
            name="token",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
