# Generated by Django 4.2.4 on 2023-08-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_telegramtoken_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramtoken",
            name="chat_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="telegramtoken",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
